### PR TITLE
generic_importer_source: apply costs when balancing

### PR DESCRIPTION
**Pull request by jakobwenzel**
The Generic Importer Source did not apply Costs at all when balancing entries. This PR tries to fix that.

### CODE REVIEW

**Comment by jbms** [comment]
Thanks.

Can you add a simple test case?

**Comment by jakobwenzel** [comment]
I added a testcase. The existing testcases for the generic source use `CSVImporter`, which cannot handle costs. Therefore, my testcase loads the transaction from a beancount file.

**Comment by jbms** [comment]
Thanks, please revert the package.json lockfile changes though.

**Comment by jakobwenzel** [comment]
Oops, that's what I get from using `git commit -a`...

**Comment by jbms** [comment]
Thanks!

**Pull request merged**
