### PR TITLE
add lines of entries for new brokerage actions

### PR DESCRIPTION
**Pull request by cookie223**
Using github.com editor in browser not sure what's changed for L1-L8.
Adding sample lines for new actions added in #120

### CODE REVIEW

**Comment by Zburatorul** [comment]
Cool. This helps. However you forgot to add the corresponding imported entries into `import_results.beancount`. This is why the tests are failing.
I recommend you run `pytest -k schwab` from the beancount_import top dir and inspect the errors. You will see it complains about the entries missing, but it also says exactly what it expects them to look like. If they look alright to you, copy-paste them into `import_results.beancount`.

**Comment by cookie223** [comment]
@carljm asked me to provide sample lines. I didn't clone the repo.

**Comment by carljm** [comment]
I can update the PR with the rest changes. Thanks for the sample lines!

**Comment by carljm** [comment]
Replaced by #125

**Pull request closed without merging**
