### PR TITLE
Add Missing Cash Balance Entries for Investments

### PR DESCRIPTION
**Pull request by patbakdev**
Add a cash balance directive for investment accounts based on the
available cash element using the first matching dated balance entry.

Added additional tests for fidelity.ofx

### CODE REVIEW

**Comment by Zburatorul** [comment]
@patbakdev, it looks like this is marked as a draft rather than ready for review. Since it's been around for a year, any other changes you want to make to it?

**Comment by patbakdev** [comment]
Not sure why I left this as draft. Possibly had trouble getting the checks to pass. I barely remember this, but looking at my local code, I have been running with this change since I open the pull request and haven't ran into any other issues. Running the test locally there is 1 failure, 1 warning, and 94 passed. The failing test seems to be with the new baseline after I merged in from master branch in August. It also looks like I made an additional fix to "Add Missing Security ID to Error List Instead of Throwing" in August after that merge, but never made a pull request for that. Give me a few days and I'll can sync the latest from master and see if I can't clean it up and resubmit.

**Comment by Zburatorul** [comment]
Looking forward to it.

**Comment by patbakdev** [comment]
It has been so long, I have trouble cherry-picking the commits. Opened new PR: Add Missing Cash Balance Entries for Investments #107

**Pull request closed without merging**
